In [16]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import re
from unicodedata import normalize

gradeCurricular = pd.read_html('https://uspdigital.usp.br/jupiterweb/listarGradeCurricular?codcg=45&codcur=45052&codhab=1&tipo=N',
                        match= "Disciplinas");

def pegaRequisitos(codigoDisciplina):
    requisitosDisciplina = pd.read_html("https://uspdigital.usp.br/jupiterweb/listarCursosRequisitos?coddis="+codigoDisciplina);
    return requisitosDisciplina

# oferecimento no formato '2s21' (2° semestre de 2021)
def pegaPassado(oferecimento):
    passadoOferecimento = pd.read_html("https://www.ime.usp.br/~pmiranda/horarios/" + oferecimento + "index.html")
    return passadoOferecimento;

## Pegando os códigos das disciplinas sendo oferecidas:

In [18]:
df = gradeCurricular[3]
df.head()

,0,1,2,3,4,5,6,7
0,Disciplinas Obrigatórias,Disciplinas Obrigatórias,Disciplinas Obrigatórias,Disciplinas Obrigatórias,Disciplinas Obrigatórias,Disciplinas Obrigatórias,Disciplinas Obrigatórias,Disciplinas Obrigatórias
1,1º Período Ideal,1º Período Ideal,Créd. Aula,Créd. Trab.,CH,CE,CP,ATPA
2,MAC0101,Integração na Universidade e na Profissão,2,0,30,NaN,NaN,NaN
3,MAC0105,Fundamentos de Matemática para a Computação,4,0,60,NaN,NaN,NaN
4,MAC0110,Introdução à Computação,4,0,60,NaN,NaN,NaN

In [57]:
codigos = [];
count = 0;
for i in df[0]:
    if(isinstance(i, str)):
        if(re.match("^(([A-Z]{3})[0-9]{4})$", i)):
            codigos.append(i); 
    count +=1;
    # Ao printar os valores de i nota-se que existem valores repetidos após 262,
    # provavelmente um erro de leftovers do jupiter;
    if(count==262):
        break;
print(codigos)

['MAC0101', 'MAC0105', 'MAC0110', 'MAC0329', 'MAT0112', 'MAT2453', 'MAC0121', 'MAC0216', 'MAC0239', 'MAE0119', 'MAT0122', 'MAT2454', 'MAC0102', 'MAC0209', 'MAC0210', 'MAC0323', 'MAT0236', 'MAC0316', 'MAC0338', 'MAC0350', 'MAC0422', 'FLC0474', 'MAC0499', 'GMG0630', 'ACH2023', 'ACH2033', 'MAC0213', 'MAC0214', 'MAC0215', 'CJE0642', 'IOF0115', 'MAC0327', 'MAC0337', 'MAC0453', 'MAE0217', 'MAE0228', 'MAE0399', 'MAP2001', 'MAT0206', 'MAT0222', 'MAT0223', 'MAT0264', 'MAC0218', 'MAC0219', 'MAC0242', 'MAC0300', 'MAC0341', 'MAC0474', 'MAE0221', 'MAE0224', 'MAE0515', 'MAT0265', 'MAT0311', 'PCS3549', 'QBQ0126', 'QBQ0230', 'QBQ0250', 'QBQ1252', 'QBQ2457', 'QBQ2503', 'QBQ2507', 'QBQ2508', 'QBQ2509', 'AUH2803', 'AUP1301', 'AUP2409', 'IOF0255', 'IOF0265', 'MAC0315', 'MAC0320', 'MAC0328', 'MAC0345', 'MAC0346', 'MAC0351', 'MAC0352', 'MAC0385', 'MAC0431', 'MAC0444', 'MAE0311', 'MAE0312', 'MAE0532', 'MAP2210', 'MAT0225', 'MAT0364', 'PCS2305', 'QBQ0102', 'QBQ0104', 'QBQ0106', 'QBQ0116', 'QBQ0204', 'QBQ0317', 'QBQ1354', 'QBQ2502', 'QBQ2505', 'ACH2096', 'ACH2106', 'MAC0317', 'MAC0318', 'MAC0325', 'MAC0331', 'MAC0332', 'MAC0340', 'MAC0343', 'MAC0344', 'MAC0375', 'MAC0412', 'MAC0414', 'MAC0417', 'MAC0420', 'MAC0425', 'MAC0426', 'MAC0441', 'MAC0448', 'MAC0450', 'MAC0470', 'MAC0471', 'MAC0473', 'MAC0475', 'MAE0325', 'MAE0328', 'MAP0313', 'MAP2220', 'MAT0234', 'MAT0350', 'PCS3345', 'PCS3863', 'ACH2007', 'ACH2066', 'ACH2067', 'ACH2076', 'ACH2077', 'ACH2087', 'ACH2107', 'ACH2117', 'ACH2127', 'ACH2137', 'MAC0322', 'MAC0333', 'MAC0336', 'MAC0413', 'MAC0416', 'MAC0427', 'MAC0430', 'MAC0432', 'MAC0436', 'MAC0438', 'MAC0439', 'MAC0446', 'MAC0451', 'MAC0452', 'MAC0456', 'MAC0459', 'MAC0464', 'MAC0466', 'MAC0467', 'MAC0468', 'MAC0472', 'MAC0546', 'MAC0690', 'MAC0691', 'MAC0693', 'MAC0775', 'MAE0314', 'MAE0315', 'MAE0326', 'MAP2310', 'MAT0330', 'MAT0359', 'PCS0216', 'PCS3529', 'PCS3848', 'ACH2028', 'ACH2037', 'ACH2038', 'ACH2048', 'ACH2068', 'ACH2078', 'ACH2086', 'ACH2098', 'ACH2108', 'ACH2118', 'MAC0319', 'MAC0326', 'MAC0419', 'MAC0424', 'MAC0434', 'MAC0435', 'MAC0447', 'MAC0458', 'MAC0460', 'MAC0463', 'MAC0465', 'MAC0485', 'MAC0536', 'MAC0552', 'MAC0692', 'MAC0776', 'MAE0330', 'MAP2321', 'MAP2411', 'PCS0210', 'PCS3858']

## Pegando os requisitos de cada disciplina:

In [55]:
cod = pegaRequisitos(codigos[6]);
req = cod[6];
req.head()

,0,1,2,3,4
0,Curso: 45051 Bacharelado em Ciência da Computa...,Curso: 45051 Bacharelado em Ciência da Computa...,Curso: 45051 Bacharelado em Ciência da Computa...,Curso: 45051 Bacharelado em Ciência da Computa...,Curso: 45051 Bacharelado em Ciência da Computa...
1,MAC0110 - Introdução à Computação,MAC0110 - Introdução à Computação,Requisito,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN
3,Curso: 45052 Bacharelado em Ciência da Computa...,Curso: 45052 Bacharelado em Ciência da Computa...,Curso: 45052 Bacharelado em Ciência da Computa...,Curso: 45052 Bacharelado em Ciência da Computa...,Curso: 45052 Bacharelado em Ciência da Computa...
4,MAC0110 - Introdução à Computação,MAC0110 - Introdução à Computação,Requisito,NaN,NaN

In [56]:
for i in req[1]:
    print(i);

Curso: 45051 Bacharelado em Ciência da Computação (diurno) - Período ideal: 2
MAC0110 - Introdução à Computação
nan
Curso: 45052 Bacharelado em Ciência da Computação (diurno) - Período ideal: 2
MAC0110 - Introdução à Computação
nan